import org.apache.hadoop.security.protocolPB.RefreshAuthorizationPolicyProtocolClientSideTranslatorPB;
public class FunctionUse6101 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolClientSideTranslatorPB refreshauthorizationpolicyprotocolclientsidetranslatorpb = new RefreshAuthorizationPolicyProtocolClientSideTranslatorPB();
}
}